### ISSUE TITLE
Add a button to Faction screen

### ISSUE THREAD

**Issue by scotty113** [Elite-Kode/elitebgs#139]
From the faction screen an "Add System" button to add that system to the ones you are watching.  I know it can be added manually, but this would make it a bit easier.  Although it will mean a long list of systems on the home page. Just an idea

**Comment by SayakMukhopadhyay** [comment]
1. If this is about adding a button to add all systems a faction is in, in a single shot then I don't think this is a good idea. It is better to just bookmark the faction page for that faction.
2. If its about adding a monitor button each the system table, one for each row, then also this is kind of difficult since the table already has a lot of data and an extra button would not really fit.

Closing this issue for now.
