### ISSUE TITLE
Performance idea - local redis caching with a separate MongoDB

### ISSUE THREAD

**Issue by vanderaj** [Elite-Kode/elitebgs#199]
Hi there, Love your work. Our faction relies on EliteBGS, and recently, around tick time, we notice that it's really struggling. 

I looked through the architecture and it's a fairly straightforward Express <> Mongoose data architecture. 

Without understanding how you've deployed this, I'm assuming it's a single instance, which might explain the slowness around tick time recently. 

I would suggest is a refactor to include a redis in memory cache in a small docker image that you can scale out using auto-scaling if your hosting has such a thing. You could fake it by spinning up say a bunch of instances just prior to the tick and kill most of them about an hour later. This would work by putting MongoDB in its own persistent instance, and then you can spin up multiple Elite BGS API servers as there's no persistent data within the API server. 

![EliteBGS architecture](https://user-images.githubusercontent.com/5029993/107885114-a9182580-6eb5-11eb-87c3-1bc1a698cc40.png)

If you're amenable, I could create a pull request that makes v5 API use this architecture whilst not moving Mongoose to its own instance, and you can test it out for performance improvements. I think it will help you a lot with scalability.

**Comment by SayakMukhopadhyay** [comment]
I am typing this out at 3am so apologise for errors. I have been having loads of performance issues the past one month, so much so that the http server itself would crash. Right now the api is not stateless as everything is built into the same nodejs app. This includes the frontend, the eddn listener and the tick socket.

Ideally, I would like the frontend be seperated into static assets served directly by nginx. Also the api can be seperated out as a seperate server from the eddn listener. Similarly the tick detector could be seperated out too. I believe this would allow me to scale the api server only.

But I dunno if there is a bottleneck in mongodb itself and I don't really see how redis can help.

Feel free to drop by the discord server if you want to have some quick discussions. I am happy to be able to discuss these issues with someone.

**Comment by vanderaj** [comment]
PR #210 addresses this idea, and the performance improvement is substantial, at the cost of slightly delayed data updates. I will add the following functionality to it and then we should integrate it:

Define if redis is to be used in a configuration area
Define the cache time in a configuration area

That way, someone who wants to test or profile uncached results can do so easily, and a custom installation can choose to disable it completely or have a shorter cache time to suit their needs.

**Comment by vanderaj** [comment]
If you also want me to add caching to V4, I can do so, but if V4 is being removed, there doesn't seem much point.

**Comment by SayakMukhopadhyay** [comment]
> Define if redis is to be used in a configuration area
> Add a check to see if Redis is running, and if not, disable caching dynamically
> Define the cache time in a configuration area
> 
> That way, someone who wants to test or profile uncached results can do so easily, and a custom installation can choose to disable it completely or have a shorter cache time to suit their needs.

Yeah, I like it very much. Especially, if I can disable redis in prod to debug stuff,

> If you also want me to add caching to V4, I can do so, but if V4 is being removed, there doesn't seem much point.

Nah, you are right that v4 is going to be removed soon so no use doing anything over that.

**Comment by SayakMukhopadhyay** [comment]
Closed by a33ad2f747d546d9a9f82b8fda8c3457e43d82a2
