### ISSUE TITLE
Add the days elapsed number for conflicts

### ISSUE THREAD

**Issue by SimpleProgrammingAU** [Elite-Kode/elitebgs#235]
Or add days at a draw. Right now, there doesn't appear to be a way to get the current duration of the conflict because draws/losses aren't counted. 

See type [`EBGSConflictFactionV5`](https://github.com/Elite-Kode/elitebgs/blob/master/backend/swaggerDefinitions/ebgs_conflict_faction_v5.js).

**Comment by SayakMukhopadhyay** [comment]
I don't really store the days lost/drawn since that data is not available through the journals. But what you _can_ do is check how many days the opponent has won. This should give you the days lost. Then use the historical API to check when the conflict started. That should give you an idea as to how many days have been drawn.
